import type { InventoryResponse } from "@/types";

export const MOCK_INVENTORY: InventoryResponse = {
  organization: {
    id: "org_vava_kigali",
    name: "Vava Transport and Logistics",
    city: "Kigali",
    supportedServiceTypes: [
      "airport_transfer",
      "corporate_event",
      "corporate_longterm",
      "vvip_transfer",
      "tour_travel",
      "destination_management",
    ],
    logoUrl: "/vava-assets/logo.png",
    active: true,
  },
  vehicles: [
    {
      id: "vava-landcruiser-prado",
      make: "Toyota",
      model: "Land Cruiser Prado",
      year: 2023,
      vehicleType: "suv",
      vehicleClass: "landcruiser",
      color: "Pearl White",
      photoUrl: "/vava-assets/landcruiser.jpeg",
      heroImage: "/vava-assets/hero-landcruiser.jpg",
      listingPhotos: ["/vava-assets/landcruiser.jpeg", "/vava-assets/hero-landcruiser.jpg"],
      dailyRateRwf: 180000,
      hourlyRateRwf: 45000,
      weeklyRateRwf: 980000,
      depositAmountRwf: 300000,
      mileageLimitKm: 180,
      extraMileageFeeRwf: 700,
      lateReturnFeeRwf: 15000,
      selfDriveEnabled: true,
      chauffeuredEnabled: true,
      rentalStatus: "available",
      listingTitle: "Land Cruiser Prado - Executive Rwanda travel",
      listingDescription:
        "A premium Land Cruiser for airport pickups, executive road trips, tourism itineraries, and high-comfort city movement.",
      listingTags: ["landcruiser", "airport", "corporate", "tourism", "safari", "vip"],
      seats: 7,
      transmission: "automatic",
      fuelType: "diesel",
    },
    {
      id: "vava-volkswagen-touareg",
      make: "Volkswagen",
      model: "Touareg V6",
      year: 2023,
      vehicleType: "suv",
      vehicleClass: "volkswagen",
      color: "Deep Black",
      photoUrl: "/vava-assets/volkswagen-service.jpg",
      heroImage: "/vava-assets/hero-volkswagen.jpg",
      listingPhotos: ["/vava-assets/volkswagen-service.jpg", "/vava-assets/hero-volkswagen.jpg"],
      dailyRateRwf: 160000,
      hourlyRateRwf: 42000,
      weeklyRateRwf: 910000,
      depositAmountRwf: 280000,
      mileageLimitKm: 180,
      extraMileageFeeRwf: 700,
      lateReturnFeeRwf: 15000,
      selfDriveEnabled: true,
      chauffeuredEnabled: true,
      rentalStatus: "available",
      listingTitle: "Volkswagen Touareg - Premium airport and corporate SUV",
      listingDescription:
        "A refined SUV for visiting executives, airport transfer programs, and discreet VVIP assignments.",
      listingTags: ["volkswagen", "airport", "corporate", "vvip", "vip"],
      seats: 5,
      transmission: "automatic",
      fuelType: "diesel",
    },
    {
      id: "vava-van-hyundai-h1",
      make: "Hyundai",
      model: "H1 Executive Van",
      year: 2022,
      vehicleType: "van",
      vehicleClass: "vans",
      color: "Black",
      photoUrl: "/vava-assets/vans.jpg",
      heroImage: "/vava-assets/hero-vans.jpg",
      listingPhotos: ["/vava-assets/vans.jpg", "/vava-assets/hero-vans.jpg"],
      dailyRateRwf: 220000,
      hourlyRateRwf: 50000,
      weeklyRateRwf: 1250000,
      depositAmountRwf: 250000,
      mileageLimitKm: 160,
      extraMileageFeeRwf: 700,
      lateReturnFeeRwf: 15000,
      selfDriveEnabled: false,
      chauffeuredEnabled: true,
      rentalStatus: "available",
      listingTitle: "Executive van for events and delegations",
      listingDescription:
        "A comfortable group vehicle for conferences, private events, airport transfers, and destination programs.",
      listingTags: ["vans", "events", "corporate", "airport", "dmc", "destination"],
      seats: 8,
      transmission: "automatic",
      fuelType: "diesel",
    },
    {
      id: "vava-sedan-e-class",
      make: "Mercedes-Benz",
      model: "E-Class",
      year: 2021,
      vehicleType: "sedan",
      vehicleClass: "sedans",
      color: "Graphite",
      photoUrl: "/vava-assets/sedans.jpg",
      heroImage: "/vava-assets/hero-sedans.jpg",
      listingPhotos: ["/vava-assets/sedans.jpg", "/vava-assets/hero-sedans.jpg"],
      dailyRateRwf: 240000,
      hourlyRateRwf: 60000,
      weeklyRateRwf: 1320000,
      depositAmountRwf: 350000,
      mileageLimitKm: 140,
      extraMileageFeeRwf: 800,
      lateReturnFeeRwf: 18000,
      selfDriveEnabled: false,
      chauffeuredEnabled: true,
      rentalStatus: "available",
      listingTitle: "Executive sedan with chauffeur",
      listingDescription:
        "A polished chauffeured sedan for VVIP concierge transfers, board visits, weddings, and protocol movements.",
      listingTags: ["sedans", "vvip", "vip", "wedding", "airport", "corporate"],
      seats: 4,
      transmission: "automatic",
      fuelType: "petrol",
    },
    {
      id: "vava-executive-bus-coaster",
      make: "Toyota",
      model: "Coaster Executive Bus",
      year: 2020,
      vehicleType: "bus",
      vehicleClass: "executive_bus",
      color: "Silver",
      photoUrl: "/vava-assets/vans-two.png",
      heroImage: "/vava-assets/hero-bus.jpg",
      listingPhotos: ["/vava-assets/vans-two.png", "/vava-assets/hero-bus.jpg"],
      dailyRateRwf: 380000,
      hourlyRateRwf: 80000,
      weeklyRateRwf: 2100000,
      depositAmountRwf: 400000,
      mileageLimitKm: 220,
      extraMileageFeeRwf: 900,
      lateReturnFeeRwf: 22000,
      selfDriveEnabled: false,
      chauffeuredEnabled: true,
      rentalStatus: "available",
      listingTitle: "Executive bus for conferences and tourism",
      listingDescription:
        "High-capacity transport for conferences, tour groups, summits, hotel shuttles, and destination management work.",
      listingTags: ["executive_bus", "events", "conference", "tourism", "dmc", "destination"],
      seats: 28,
      transmission: "manual",
      fuelType: "diesel",
    },
  ],
};
